mezzanine_recipes/urls.py
from django.conf.urls.defaults import patterns, url

from mezzanine.conf import settings


# Blog patterns.
urlpatterns = patterns("mezzanine_recipes.views",
    url("^%s/(?P<year>\d{4})/(?P<month>\d{1,2})/(?P<day>\d{1,2})/(?P<slug>.*)/$" % settings.RECIPES_SLUG, "blog_post_detail", {'template': 'recipe_detail.html',}, name="blog_post_detail_date"),
    url("^%s/(?P<slug>.*)/$" % settings.RECIPES_SLUG, "blog_post_detail", {'template': 'recipe_detail.html',}, name="blog_post_detail"),
    url("^%s/(?P<year>\d{4})/(?P<month>\d{1,2})/(?P<day>\d{1,2})/(?P<slug>.*)/$" % settings.ARTICLES_SLUG, "blog_post_detail", name="blog_post_detail_date"),
    url("^%s/(?P<slug>.*)/$" % settings.ARTICLES_SLUG, "blog_post_detail", name="blog_post_detail"),
    url("^%s/$" % settings.RECIPES_SLUG, "blog_post_list_recipe", name="blog_post_list"),
    url("^%s/$" % settings.ARTICLES_SLUG, "blog_post_list_article", name="blog_post_list"),

    url("^feeds/(?P<format>.*)/$", "blog_post_feed", name="blog_post_feed"),
    url("^tag/(?P<tag>.*)/feeds/(?P<format>.*)/$", "blog_post_feed", name="blog_post_feed_tag"),
    url("^tag/(?P<tag>.*)/$", "blog_post_list", name="blog_post_list_tag"),
    url("^category/(?P<category>.*)/feeds/(?P<format>.*)/$", "blog_post_feed", name="blog_post_feed_category"),
    url("^category/(?P<category>.*)/$", "blog_post_list", name="blog_post_list_category"),
    url("^author/(?P<username>.*)/feeds/(?P<format>.*)/$", "blog_post_feed", name="blog_post_feed_author"),
    url("^author/(?P<username>.*)/$", "blog_post_list", name="blog_post_list_author"),
    url("^archive/(?P<year>\d{4})/(?P<month>\d{1,2})/$", "blog_post_list", name="blog_post_list_month"),
    url("^archive/(?P<year>.*)/$", "blog_post_list", name="blog_post_list_year"),
    url("^(?P<year>\d{4})/(?P<month>\d{1,2})/(?P<day>\d{1,2})/(?P<slug>.*)/$", "blog_post_detail", name="blog_post_detail_date"),
    url("^(?P<slug>.*)/$", "blog_post_detail", name="blog_post_detail"),
    url("^$", "blog_post_list", name="blog_post_list"),
)

mezzanine_recipes/models.py
from django.db import models
from django.db.models.query import QuerySet
from django.utils.translation import ugettext_lazy as _
from django.contrib.contenttypes.models import ContentType

from mezzanine.conf import settings
from mezzanine.core.models import Orderable
from mezzanine.core.managers import DisplayableManager
from mezzanine.blog.models import BlogPost as MezzanineBlogPost
from mezzanine.utils.timezone import now

from . import fields


class SubclassingQuerySet(QuerySet):

    def __getitem__(self, k):
        result = super(SubclassingQuerySet, self).__getitem__(k)
        if isinstance(result, BlogProxy) :
            return result.as_leaf_class()
        else :
            return result

    def __iter__(self):
        for item in super(SubclassingQuerySet, self).__iter__():
            yield item.as_leaf_class()


class BlogManager(DisplayableManager):
    def get_query_set(self):
        return SubclassingQuerySet(self.model)



class BlogProxy(MezzanineBlogPost):
    content_type = models.ForeignKey(ContentType,editable=False,null=True)
    modified_date = models.DateTimeField(_("Last Modified"), blank=True, null=True)

    template_dir = "blog/"
    secondary = BlogManager()

    def save(self, *args, **kwargs):
        self.modified_date = now()
        if not self.content_type:
            self.content_type = ContentType.objects.get_for_model(self.__class__)
        super(BlogProxy, self).save(*args, **kwargs)

    def as_leaf_class(self):
        content_type = self.content_type
        model = content_type.model_class()
        if model == BlogProxy:
            return self
        return model.objects.get(id=self.id)

    def _get_next_or_previous_by_publish_date(self, is_next, **kwargs):
        """
        Retrieves next or previous object by publish date. We implement
        our own version instead of Django's so we can hook into the
        published manager and concrete subclasses.
        """
        arg = "publish_date__gt" if is_next else "publish_date__lt"
        order = "publish_date" if is_next else "-publish_date"
        lookup = {arg: self.publish_date}
        concrete_model = self.__class__
        try:
            queryset = concrete_model.secondary.published
        except AttributeError:
            queryset = concrete_model.secondary.all
        try:
            return queryset(**kwargs).filter(**lookup).order_by(order)[0]
        except IndexError:
            pass


class BlogPost(BlogProxy):
    secondary = BlogManager()

    @models.permalink
    def get_absolute_url(self):
        url_name = "blog_post_detail"
        kwargs = {"slug": "%s/%s" % (settings.ARTICLES_SLUG, self.slug)}
        if settings.BLOG_URLS_USE_DATE:
            url_name = "blog_post_detail_date"
            month = str(self.publish_date.month)
            if len(month) == 1:
                month = "0" + month
            day = str(self.publish_date.day)
            if len(day) == 1:
                day = "0" + day
            kwargs.update({
                "day": day,
                "month": month,
                "year": self.publish_date.year,
                })
        return (url_name, (), kwargs)

    class Meta:
        verbose_name = _("Blog post")
        verbose_name_plural = _("Blog posts")
        ordering = ("-publish_date",)


class Recipe(BlogProxy):
    """
    Implements the recipe type of page with all recipe fields.
    """
    summary = models.TextField(_("Summary"), blank=True, null=True)
    portions = models.IntegerField(_("Portions"), blank=True, null=True)
    difficulty = models.IntegerField(_("Difficulty"), choices=fields.DIFFICULTIES, blank=True, null=True)
    source = models.URLField(_("Source"), blank=True, null=True, help_text=_("URL of the source recipe"))

    template_dir = "recipe/"
    secondary = BlogManager()
    search_fields = ("title", "summary", "description",)

    def __unicode__(self):
        return u'%s' % (self.title)

    @models.permalink
    def get_absolute_url(self):
        url_name = "blog_post_detail"
        kwargs = {"slug": "%s/%s" % (settings.RECIPES_SLUG, self.slug)}
        if settings.BLOG_URLS_USE_DATE:
            url_name = "blog_post_detail_date"
            month = str(self.publish_date.month)
            if len(month) == 1:
                month = "0" + month
            day = str(self.publish_date.day)
            if len(day) == 1:
                day = "0" + day
            kwargs.update({
                "day": day,
                "month": month,
                "year": self.publish_date.year,
                })
        return (url_name, (), kwargs)

    class Meta:
        verbose_name = _("Recipe")
        verbose_name_plural = _("Recipes")
        ordering = ("-publish_date",)


class Ingredient(Orderable):
    """
    Provides ingredient fields for managing recipe content and making
    it searchable.
    """
    recipe = models.ForeignKey("Recipe", verbose_name=_("Recipe"), related_name="ingredients")
    quantity = models.CharField(_("Quantity"), max_length=10, blank=True, null=True)
    unit = models.IntegerField(_("Unit"), choices=fields.UNITS, blank=True, null=True)
    ingredient = models.CharField(_("Ingredient"), max_length=100)
    note = models.CharField(_("Note"), max_length=200, blank=True, null=True)

    def __unicode__(self):
        _ingredient = u'%s' % (self.ingredient)

        if self.unit:
            _ingredient = u'%s %s' % (self.get_unit_display(), _ingredient)

        if self.quantity:
            _ingredient = u'%s %s' % (self.quantity, _ingredient)

        if len(self.note):
           _ingredient = u'%s - %s' % (_ingredient, self.note)

        return _ingredient

    class Meta:
        verbose_name = _("Ingredient")
        verbose_name_plural = _("Ingredients")


class Period(models.Model):
    """
    Provides fields for a period of time
    """
    hours = models.IntegerField(_("hours"), default=0)
    minutes = models.IntegerField(_("minutes"), default=0)

    def __unicode__(self):
        return "%02d:%02d" %(self.hours, self.minutes)

    class Meta:
        abstract = True


class WorkingHours(Period):
    """
    Provides working hour fields for cooking a recipe
    """
    recipe = models.OneToOneField("Recipe", verbose_name=_("Recipe"), related_name="working_hours")

    class Meta:
        verbose_name = _("working hour")
        verbose_name_plural = verbose_name


class CookingTime(Period):
    """
    Provides cooking time fields for cooking a recipe
    """
    recipe = models.OneToOneField("Recipe", verbose_name=_("Recipe"), related_name="cooking_time")

    class Meta:
        verbose_name = _("cooking time")
        verbose_name_plural = verbose_name


class RestPeriod(Period):
    """
    Provides rest time fields for cooking a recipe
    """
    recipe = models.OneToOneField("Recipe", verbose_name=_("Recipe"), related_name="rest_period")
    days = models.IntegerField(_("days"), default=0)

    def __unicode__(self):
        period = super(RestPeriod, self).__unicode__()
        return "%02d:%s" %(self.days, period)

    class Meta:
        verbose_name = _("rest period")
        verbose_name_plural = verbose_name

mezzanine_recipes/templates/recipe/blog_post_detail.html
{% overextends "blog/blog_post_detail.html" %}

{% load mezzanine_tags i18n %}

{% block blog_post_detail_featured_image %}
    {% if blog_post.featured_image %}
        <p><img src="{{ MEDIA_URL }}{% thumbnail blog_post.featured_image 720 0 %}"></p>
    {% endif %}
{% endblock %}

{% block extension_2 %}
{{ block.super }}

{% block recipe_hero %}
<div class="hero-unit">

    {% block recipe_summary %}
    {% if blog_post.summary %}
        {% editable blog_post.summary %}<p>{{ blog_post.summary }}</p>{% endeditable %}
    {% endif %}
    {% endblock %}

    {% block recipe_ingredients %}
    {% if blog_post.ingredients.count %}
        <dl class="dl-horizontal ingredients">
            <h4><dt>{% trans 'Ingredients' %}:</dt></h4>
            {% for ingredient in blog_post.ingredients.all %}
                <dd>{{ ingredient }}</dd>
            {% endfor %}
        </dl>
    {% endif %}
    {% endblock %}

    {% block recipe_portions %}
    {% if blog_post.portions %}
        {% editable blog_post.portions %}
            <dl class="dl-horizontal">
                <h4><dt>{% trans 'Portions' %}:</dt></h4>
                <dd>{{ blog_post.portions }}</dd>
            </dl>
        {% endeditable %}
    {% endif %}
    {% endblock %}

    {% block recipe_difficulty %}
    {% if blog_post.difficulty %}
        {% editable blog_post.difficulty %}
            <dl class="dl-horizontal">
                <h4><dt>{% trans 'Difficulty' %}:</dt></h4>
                <dd>{{ blog_post.get_difficulty_display }}</dd>
            </dl>
        {% endeditable %}
    {% endif %}
    {% endblock %}

    {% block recipe_working_hours %}
    {% if blog_post.working_hours %}
        <dl class="dl-horizontal">
            <h4><dt>{% trans 'Working Hours' %}:</dt></h4>
            <dd>
                {% if blog_post.working_hours.hours %}
                    {% blocktrans count hours=blog_post.working_hours.hours %}
                        {{ hours }} Hour
                    {% plural %}
                        {{ hours }} Hours
                    {% endblocktrans %}
                {% endif %}

                {% blocktrans count minutes=blog_post.working_hours.minutes %}
                    {{ minutes }} Minute
                {% plural %}
                    {{ minutes }} Minutes
                {% endblocktrans %}
            </dd>
        </dl>
    {% endif %}
    {% endblock %}

    {% block recipe_cooking_time %}
    {% if blog_post.cooking_time %}
        <dl class="dl-horizontal">
            <h4><dt>{% trans 'Cooking Time' %}:</dt></h4>
            <dd>
                {% if blog_post.cooking_time.hours %}
                    {% blocktrans count hours=blog_post.cooking_time.hours %}
                        {{ hours }} Hour
                    {% plural %}
                        {{ hours }} Hours
                    {% endblocktrans %}
                {% endif %}

                {% blocktrans count minutes=blog_post.cooking_time.minutes %}
                    {{ minutes }} Minute
                {% plural %}
                    {{ minutes }} Minutes
                {% endblocktrans %}
            </dd>
        </dl>
    {% endif %}
    {% endblock %}

    {% block recipe_rest_period %}
    {% if blog_post.rest_period %}
        <dl class="dl-horizontal">
            <h4><dt>{% trans 'Rest Period' %}:</dt></h4>
            <dd>
                {% if blog_post.rest_period.days %}
                    {% blocktrans count days=blog_post.rest_period.days %}
                        {{ days }} Day
                    {% plural %}
                        {{ days }} Days
                    {% endblocktrans %}
                {% endif %}

                {% if blog_post.rest_period.hours %}
                    {% blocktrans count hours=blog_post.rest_period.hours %}
                        {{ hours }} Hour
                    {% plural %}
                        {{ hours }} Hours
                    {% endblocktrans %}
                {% endif %}

                {% blocktrans count minutes=blog_post.rest_period.minutes %}
                    {{ minutes }} Minute
                {% plural %}
                    {{ minutes }} Minutes
                {% endblocktrans %}
            </dd>
        </dl>
    {% endif %}
    {% endblock %}

</div>
{% endblock %}
{% endblock %}

mezzanine_recipes/templates/recipe/recipe_detail.html
{% extends "blog/blog_post_detail.html" %}

{% load mezzanine_tags i18n %}

{% block blog_post_detail_featured_image %}
    {% if blog_post.featured_image %}
        <p><img src="{{ MEDIA_URL }}{% thumbnail blog_post.featured_image 720 0 %}"></p>
    {% endif %}
{% endblock %}

{% block extension_2 %}
{{ block.super }}

{% block recipe_hero %}
<div class="hero-unit">

    {% block recipe_summary %}
    {% if blog_post.summary %}
        {% editable blog_post.summary %}<p>{{ blog_post.summary }}</p>{% endeditable %}
    {% endif %}
    {% endblock %}

    {% block recipe_ingredients %}
    {% if blog_post.ingredients.count %}
        <dl class="dl-horizontal ingredients">
            <h4><dt>{% trans 'Ingredients' %}:</dt></h4>
            {% for ingredient in blog_post.ingredients.all %}
                <dd>{{ ingredient }}</dd>
            {% endfor %}
        </dl>
    {% endif %}
    {% endblock %}

    {% block recipe_portions %}
    {% if blog_post.portions %}
        {% editable blog_post.portions %}
            <dl class="dl-horizontal">
                <h4><dt>{% trans 'Portions' %}:</dt></h4>
                <dd>{{ blog_post.portions }}</dd>
            </dl>
        {% endeditable %}
    {% endif %}
    {% endblock %}

    {% block recipe_difficulty %}
    {% if blog_post.difficulty %}
        {% editable blog_post.difficulty %}
            <dl class="dl-horizontal">
                <h4><dt>{% trans 'Difficulty' %}:</dt></h4>
                <dd>{{ blog_post.get_difficulty_display }}</dd>
            </dl>
        {% endeditable %}
    {% endif %}
    {% endblock %}

    {% block recipe_working_hours %}
    {% if blog_post.working_hours %}
        <dl class="dl-horizontal">
            <h4><dt>{% trans 'Working Hours' %}:</dt></h4>
            <dd>
                {% if blog_post.working_hours.hours %}
                    {% blocktrans count hours=blog_post.working_hours.hours %}
                        {{ hours }} Hour
                    {% plural %}
                        {{ hours }} Hours
                    {% endblocktrans %}
                {% endif %}

                {% blocktrans count minutes=blog_post.working_hours.minutes %}
                    {{ minutes }} Minute
                {% plural %}
                    {{ minutes }} Minutes
                {% endblocktrans %}
            </dd>
        </dl>
    {% endif %}
    {% endblock %}

    {% block recipe_cooking_time %}
    {% if blog_post.cooking_time %}
        <dl class="dl-horizontal">
            <h4><dt>{% trans 'Cooking Time' %}:</dt></h4>
            <dd>
                {% if blog_post.cooking_time.hours %}
                    {% blocktrans count hours=blog_post.cooking_time.hours %}
                        {{ hours }} Hour
                    {% plural %}
                        {{ hours }} Hours
                    {% endblocktrans %}
                {% endif %}

                {% blocktrans count minutes=blog_post.cooking_time.minutes %}
                    {{ minutes }} Minute
                {% plural %}
                    {{ minutes }} Minutes
                {% endblocktrans %}
            </dd>
        </dl>
    {% endif %}
    {% endblock %}

    {% block recipe_rest_period %}
    {% if blog_post.rest_period %}
        <dl class="dl-horizontal">
            <h4><dt>{% trans 'Rest Period' %}:</dt></h4>
            <dd>
                {% if blog_post.rest_period.days %}
                    {% blocktrans count days=blog_post.rest_period.days %}
                        {{ days }} Day
                    {% plural %}
                        {{ days }} Days
                    {% endblocktrans %}
                {% endif %}

                {% if blog_post.rest_period.hours %}
                    {% blocktrans count hours=blog_post.rest_period.hours %}
                        {{ hours }} Hour
                    {% plural %}
                        {{ hours }} Hours
                    {% endblocktrans %}
                {% endif %}

                {% blocktrans count minutes=blog_post.rest_period.minutes %}
                    {{ minutes }} Minute
                {% plural %}
                    {{ minutes }} Minutes
                {% endblocktrans %}
            </dd>
        </dl>
    {% endif %}
    {% endblock %}

</div>
{% endblock %}
{% endblock %}

mezzanine_recipes/templates/recipe/recipe_list.html
{% extends "blog/blog_post_list.html" %}